### ISSUE TITLE
Webapp Plugin: Front-end build fails on initial build

### ISSUE THREAD

**Issue by codeviking** [allenai/sbt-plugins#169]
@ekolve and a few interns have experienced this (possibly non-deterministically) -- but the very first `reStart` on a fresh repository appears to fail to build the front-end into `public`.

**Comment by markschaake** [comment]
I've noticed this too

**Comment by jkinkead** [comment]
Does it need the directory to exist before it starts?

**Comment by codeviking** [comment]
The `javascript` / `gulp` side shouldn't.  It'll create the missing directory.

**Comment by codeviking** [comment]
This appears to be some sort of weird race condition.  I just experienced it with a fresh checkout of aristo.

The files are actually generated correctly -- I think it's that the spray server starts up prior to the directory being generated?

**Comment by jkinkead** [comment]
That would totally make sense.

If we added a dependency to `re-start` that created the public directory, it would fix that particular problem.

**Comment by jkinkead** [comment]
I fixed this with a couple of changes: Syrup no longer deletes the whole `public` directory on npm builds, and the directory is created before the npm build begins.

The problem was caused within `spray-routing`: It holds a reference to the directory that's created on server start. If that directory goes away (or is removed & recreated, or didn't exist in the first place), it'll hold a reference to a bad location, and will try to find files in there.

**Comment by codeviking** [comment]
Nicely done!  Glad to get this fixed.  I tend to be a bit overzealous with my `cleaning`!
